# Generated by Django 4.0.4 on 2022-04-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='unit_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='ingredientID',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('L', 'lbs'), ('P', 'pnds'), ('G', 'grams')], max_length=1),
        ),
    ]
