# Generated by Django 4.0.4 on 2022-04-19 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_menuitem_ingredient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='ingredient',
            field=models.CharField(default='salt', max_length=25),
            preserve_default=False,
        ),
    ]
